
export const GLOBAL_TOGGLE_IS_MOBILE            = 'GLOBAL_TOGGLE_IS_MOBILE';
export const GLOBAL_TOGGLE_SIDE_BAR             = 'GLOBAL_TOGGLE_SIDE_BAR';
export const GLOBAL_TOGGLE_EPISODE_SORT         = 'GLOBAL_TOGGLE_EPISODE_SORT';
export const GLOBAL_TOGGLE_RELEASE_DATE_SORT    = 'GLOBAL_TOGGLE_RELEASE_DATE_SORT';